# Generated by Django 4.1.13 on 2023-11-08 10:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('vip', models.BooleanField(default=False)),
                ('saldo', models.PositiveIntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Nombres',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('producto_modelo', models.CharField(max_length=50)),
                ('producto_unidades', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('vip', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.marca')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'unique_together': {('producto_modelo', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('referencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('compra_unidades', models.PositiveIntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('iva', models.DecimalField(decimal_places=2, default=0.21, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.cliente')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
