# Generated by Django 4.1.13 on 2023-12-13 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'Marcas'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_unidades',
            new_name='unidades',
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compra',
            name='unidades',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('fecha', 'producto', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('marca', 'modelo')},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='compra_unidades',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
    ]
