# Generated by Django 4.1.13 on 2023-12-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_marca_options_rename_usuario_cliente_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='marca_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
